### ISSUE TITLE
Add .editorconfig http://editorconfig.org/

### ISSUE THREAD

**Issue by beardcoder** [beardcoder/frontend-kickstart#2]
## Expected Behavior
As a developer I want the IDE to adapt automatically to the codestyle (css, js, html)

## Actual Behavior
Nothing

## Steps to Reproduce the Problem

  1. Use the .editorconfig plugin in PHPStorm
  2. Open a CSS File
  3. Reformat this file

**Comment by hisk** [comment]
I'd like to take this one if it's ok.
