### ISSUE TITLE
Add github issue template

### ISSUE THREAD

**Issue by beardcoder** [beardcoder/frontend-kickstart#3]
## Expected Behavior

As contributer i wand a well-defined issue like https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md

## Steps to Reproduce the Problem

  1. Create new issue on guthub

**Comment by marioidival** [comment]
I can help you!

**Comment by beardcoder** [comment]
Hey :) big thx.

I want an scrum|userstory like issue template.
For example https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md or https://github.com/TalAter/open-source-templates/blob/master/ISSUE_TEMPLATE.md
